#!/usr/bin/env python3
"""
コード相互レビューエージェント

Claude と GPT が相互にコードをレビューし、
最終的に一つの高品質なコードをアウトプットするエージェント

GitHub Copilot SDK を使用した実装
- GitHub Copilot経由でLLM（GPT/Claude）にアクセス
- 別途APIキー不要（GitHub Copilotサブスクリプションで利用可能）
"""

import asyncio
import sys
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.markdown import Markdown

# パスを追加
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from agentic_workflow.agent import AgentConfig, AgenticWorkflow

console = Console()


class ReviewPhase(Enum):
    """レビューフェーズ"""
    INITIAL_CODE = "initial_code"
    REVIEW = "review"
    REVISION = "revision"
    FINAL_MERGE = "final_merge"


@dataclass
class CodeReviewResult:
    """コードレビューの結果"""
    model: str
    phase: ReviewPhase
    code: str
    review_comments: list[str] = field(default_factory=list)
    score: int = 0


@dataclass
class FinalCodeOutput:
    """最終的なコード出力"""
    code: str
    merged_from: list[str]
    total_review_rounds: int
    improvements: list[str]


class CodeReviewOrchestrator:
    """
    コード相互レビューオーケストレーター

    GitHub Copilot SDK を使用して、2つの異なるLLMモデルが
    相互にコードをレビューし、最終的に一つの高品質なコードを生成する

    特徴:
    - GitHub Copilot経由でLLMにアクセス（別途APIキー不要）
    - 複数モデル（GPT/Claude）の切り替えが可能
    - MCPサーバーとの連携も可能
    """

    # GitHub Copilotが提供するモデル
    CLAUDE_MODEL = "claude-sonnet-4-20250514"
    GPT_MODEL = "gpt-4.1"

    def __init__(self, max_review_rounds: int = 2, verbose: bool = True):
        self.max_review_rounds = max_review_rounds
        self.verbose = verbose
        self.review_history: list[CodeReviewResult] = []

    def _create_code_generator_config(self, model: str) -> AgentConfig:
        """コード生成用エージェント設定を作成"""
        model_name = "Claude" if "claude" in model else "GPT"

        return AgentConfig(
            name=f"Code Generator ({model_name})",
            description=f"{model_name} code generation agent",
            model=model,
            prompt=f"""You are an excellent software engineer.
Generate high-quality, maintainable code based on user requirements.

## Coding Guidelines
- Write clean and readable code
- Add appropriate comments
- Consider error handling
- Use type hints (for Python)
- Follow SOLID principles

## Output Format
Always wrap code in ```language and ``` blocks.
After the code, briefly explain the implementation points.

You are {model_name} ({model}).""",
            mcp_servers={},
        )

    def _create_code_reviewer_config(self, model: str, reviewing_model: str) -> AgentConfig:
        """コードレビュー用エージェント設定を作成"""
        model_name = "Claude" if "claude" in model else "GPT"
        target_model = "GPT" if "claude" in model else "Claude"

        return AgentConfig(
            name=f"Code Reviewer ({model_name})",
            description=f"{model_name} code review agent",
            model=model,
            prompt=f"""You are a skilled code reviewer.
Review the code generated by {target_model} and suggest improvements.

## Review Criteria
1. **Correctness**: Does the code meet requirements?
2. **Readability**: Is the code easy to read and understand?
3. **Efficiency**: Are there any performance issues?
4. **Security**: Are there any security concerns?
5. **Best Practices**: Does it follow language/framework conventions?
6. **Error Handling**: Is exception handling appropriate?
7. **Testability**: Is the design easy to test?

## Output Format
Output the review result in the following format:

### Score: [0-100]

### Good Points
- ...

### Improvements
- ...

### Suggested Fix
```language
(improved code)
```

You are {model_name} ({model}). Please provide constructive feedback.""",
            mcp_servers={},
        )

    def _create_merge_config(self) -> AgentConfig:
        """最終マージ用エージェント設定を作成"""
        return AgentConfig(
            name="Code Merger",
            description="Merge multiple review results to generate final code",
            model=self.CLAUDE_MODEL,
            prompt="""You are a code integration expert.
Analyze the review results and suggestions from multiple models,
and generate the final code by combining the best elements.

## Integration Policy
1. Incorporate good points from both models
2. Resolve all identified issues
3. Maintain code consistency
4. Choose the cleanest and most efficient implementation

## Output Format
### Final Code
```language
(integrated code)
```

### Adopted Improvements
- From Claude: ...
- From GPT: ...

### Final Score: [0-100]
""",
            mcp_servers={},
        )

    async def _generate_initial_code(self, request: str, model: str) -> CodeReviewResult:
        """初期コードを生成（GitHub Copilot SDK経由）"""
        model_name = "Claude" if "claude" in model else "GPT"
        self._log(f"[{model_name}] Generating initial code...", style="bold blue")

        config = self._create_code_generator_config(model)

        async with AgenticWorkflow(config, verbose=False) as agent:
            result = await agent.run(f"Generate code for the following request:\n\n{request}")

            review_result = CodeReviewResult(
                model=model,
                phase=ReviewPhase.INITIAL_CODE,
                code=result.response,
            )
            self.review_history.append(review_result)

            self._log(f"[{model_name}] Initial code generation complete", style="green")
            return review_result

    async def _review_code(
        self,
        code: str,
        original_request: str,
        reviewer_model: str,
        author_model: str,
    ) -> CodeReviewResult:
        """コードをレビュー（GitHub Copilot SDK経由）"""
        reviewer_name = "Claude" if "claude" in reviewer_model else "GPT"
        author_name = "GPT" if "claude" in reviewer_model else "Claude"

        self._log(f"[{reviewer_name}] Reviewing {author_name}'s code...", style="bold yellow")

        config = self._create_code_reviewer_config(reviewer_model, author_model)

        review_prompt = f"""## Original Request
{original_request}

## Code to Review (generated by {author_name})
{code}

Review the above code and suggest improvements if needed."""

        async with AgenticWorkflow(config, verbose=False) as agent:
            result = await agent.run(review_prompt)

            review_result = CodeReviewResult(
                model=reviewer_model,
                phase=ReviewPhase.REVIEW,
                code=result.response,
            )
            self.review_history.append(review_result)

            self._log(f"[{reviewer_name}] Review complete", style="green")
            return review_result

    async def _merge_reviews(
        self,
        original_request: str,
        claude_code: str,
        claude_review: str,
        gpt_code: str,
        gpt_review: str,
    ) -> FinalCodeOutput:
        """レビュー結果をマージして最終コードを生成"""
        self._log("Merging review results...", style="bold magenta")

        config = self._create_merge_config()

        merge_prompt = f"""## Original Request
{original_request}

## Claude's Generated Code
{claude_code}

## GPT's Review of Claude's Code
{gpt_review}

## GPT's Generated Code
{gpt_code}

## Claude's Review of GPT's Code
{claude_review}

Analyze all the above code and reviews, and generate the final code incorporating the best elements from both."""

        async with AgenticWorkflow(config, verbose=False) as agent:
            result = await agent.run(merge_prompt)

            self._log("Merge complete", style="green")

            return FinalCodeOutput(
                code=result.response,
                merged_from=[self.CLAUDE_MODEL, self.GPT_MODEL],
                total_review_rounds=len(self.review_history),
                improvements=[
                    "Integrated reviews from both Claude and GPT",
                    "Applied best practices",
                    "Ensured code consistency",
                ],
            )

    async def run(self, code_request: str) -> FinalCodeOutput:
        """
        コード相互レビューワークフローを実行

        GitHub Copilot SDK経由で:
        1. Claude と GPT がそれぞれ初期コードを生成
        2. 互いのコードをレビュー
        3. レビュー結果を統合して最終コードを生成
        """
        self._log_header(code_request)

        # Phase 1: 初期コード生成（並列実行）
        self._log_phase("Phase 1: Initial Code Generation")
        claude_initial, gpt_initial = await asyncio.gather(
            self._generate_initial_code(code_request, self.CLAUDE_MODEL),
            self._generate_initial_code(code_request, self.GPT_MODEL),
        )

        # Phase 2: 相互レビュー（並列実行）
        self._log_phase("Phase 2: Cross Review")
        claude_reviews_gpt, gpt_reviews_claude = await asyncio.gather(
            self._review_code(
                gpt_initial.code,
                code_request,
                self.CLAUDE_MODEL,
                self.GPT_MODEL,
            ),
            self._review_code(
                claude_initial.code,
                code_request,
                self.GPT_MODEL,
                self.CLAUDE_MODEL,
            ),
        )

        # Phase 3: 最終マージ
        self._log_phase("Phase 3: Final Code Generation")
        final_output = await self._merge_reviews(
            original_request=code_request,
            claude_code=claude_initial.code,
            claude_review=claude_reviews_gpt.code,
            gpt_code=gpt_initial.code,
            gpt_review=gpt_reviews_claude.code,
        )

        self._log_result(final_output)

        return final_output

    def _log(self, message: str, style: str = "") -> None:
        """ログ出力"""
        if self.verbose:
            console.print(f"[{style}]{message}[/{style}]" if style else message)

    def _log_header(self, request: str) -> None:
        """ヘッダーを表示"""
        if self.verbose:
            console.print(
                Panel.fit(
                    "[bold]Code Mutual Review Agent[/bold]\n"
                    "[dim]Claude x GPT (via GitHub Copilot SDK)[/dim]\n\n"
                    f"Request: {request[:100]}{'...' if len(request) > 100 else ''}",
                    border_style="cyan",
                )
            )

    def _log_phase(self, phase: str) -> None:
        """フェーズを表示"""
        if self.verbose:
            console.print(f"\n[bold blue]{'='*60}[/bold blue]")
            console.print(f"[bold blue]> {phase}[/bold blue]")
            console.print(f"[bold blue]{'='*60}[/bold blue]")

    def _log_result(self, output: FinalCodeOutput) -> None:
        """最終結果を表示"""
        if self.verbose:
            console.print(f"\n[bold green]{'='*60}[/bold green]")
            console.print("[bold green]Final Code Generation Complete[/bold green]")
            console.print(f"[bold green]{'='*60}[/bold green]")

            table = Table(title="Review Statistics")
            table.add_column("Item", style="cyan")
            table.add_column("Value", style="white")

            table.add_row("Total Reviews", str(output.total_review_rounds))
            table.add_row("Merged Models", ", ".join(output.merged_from))
            table.add_row("Improvements", str(len(output.improvements)))

            console.print(table)

            console.print("\n[bold]Final Code:[/bold]")
            console.print(Panel(
                Markdown(output.code),
                border_style="green",
            ))


async def main() -> None:
    """コード相互レビューエージェントデモを実行"""

    console.print(
        Panel.fit(
            "[bold]Code Mutual Review Agent[/bold]\n"
            "[dim]Claude x GPT Cross Review[/dim]\n\n"
            "[cyan]Accessing LLM via GitHub Copilot SDK[/cyan]\n"
            "[dim](No additional API keys required)[/dim]",
            border_style="magenta",
        )
    )

    code_request = """
Implement an async HTTP client class in Python with the following features:

1. Support GET/POST/PUT/DELETE methods
2. Automatic retry with exponential backoff (max 3 attempts)
3. Timeout configuration
4. Automatic JSON response parsing
5. Custom header support
6. Proper error handling
"""

    orchestrator = CodeReviewOrchestrator(max_review_rounds=2, verbose=True)

    try:
        result = await orchestrator.run(code_request)

        console.print("\n[bold green]Code generation complete![/bold green]")

    except Exception as e:
        console.print(f"\n[bold red]Error: {e}[/bold red]")
        console.print("\n[yellow]Hint: Make sure you are authenticated with GitHub Copilot CLI[/yellow]")
        console.print("  gh auth login")
        console.print("  gh extension install github/gh-copilot")
        raise


if __name__ == "__main__":
    asyncio.run(main())
